"""Render the README's status block from the register.

The README's claims about what is decided and what is built are not prose
anyone remembers to update: they are generated from ``docs/adr/index.json``
by this script and pinned by ``tests/test_adr_index.py``, which also refuses
a decision word (Proposed, Accepted, Superseded) anywhere in the README
outside the generated block. Review round 2 (ChatGPT, mutation R03) showed
that a free sentence claiming the whole Security Division was accepted,
built and deployed left the suite green; this is the remedy the families
converged on, generate the public summary rather than check free prose.

    python docs/adr/render_status.py            # print the block
    python docs/adr/render_status.py --write    # splice it into README.md
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
INDEX_PATH = ROOT / "docs" / "adr" / "index.json"
README_PATH = ROOT / "README.md"
BEGIN = "<!-- adr-status:begin (generated by docs/adr/render_status.py; do not edit by hand) -->"
END = "<!-- adr-status:end -->"

DECISION_WORDS = {
    "Proposed": "Proposed (written, not yet adopted)",
    "Accepted": "Accepted",
    "Superseded": "Superseded",
}
IMPLEMENTATION_WORDS = {
    "not-code": "nothing to build",
    "none": "not built",
    "partial": "partly built",
    "reference-unwired": "a reference port in the tree, deliberately unwired",
    "built": "built",
}


def render(index: dict | None = None) -> str:
    """The block, as text, with the markers on its first and last lines."""
    data = json.loads(INDEX_PATH.read_text(encoding="utf-8")) if index is None else index
    records = sorted(data["records"], key=lambda r: r["number"])
    lines = [
        BEGIN,
        "",
        "Every architecture decision record carries two statuses in a machine-checked",
        "register ([`docs/adr/index.json`](docs/adr/index.json), enforced by",
        "`tests/test_adr_index.py`): what was decided (Proposed, Accepted, Superseded)",
        "and what the tree does about it (not-code, none, partial, reference-unwired,",
        "built). Proposed is never read as Accepted, and Accepted is never read as",
        "built. This list is generated from the register; the suite fails if it is",
        "edited by hand or if a status claim appears anywhere else on this page.",
        "",
    ]
    for record in records:
        number = record["number"]
        decision = DECISION_WORDS[record["decision"]]
        implementation = IMPLEMENTATION_WORDS[record["implementation"]]
        note = " ".join(str(record.get("notes", "")).split())
        entry = (
            f"- [ADR-{number}](docs/adr/{record['file']}) — {record['title']}. "
            f"**{decision}; {implementation}.**"
        )
        if note:
            entry += f" {note}"
        lines.append(entry)
    reserved = data.get("reserved", [])
    if reserved:
        held = "; ".join(f"ADR-{r['number']} ({r['held_for']})" for r in sorted(reserved, key=lambda r: r["number"]))
        lines.extend(["", f"Numbers held for records not yet written: {held}."])
    lines.extend(["", END])
    return "\n".join(lines)


def splice(readme: str, block: str) -> str:
    """Replace the block between the markers; the markers must exist once each."""
    start = readme.index(BEGIN)
    end = readme.index(END, start) + len(END)
    return readme[:start] + block + readme[end:]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="splice the block into README.md")
    args = parser.parse_args(argv)
    block = render()
    if args.write:
        readme = README_PATH.read_text(encoding="utf-8")
        README_PATH.write_text(splice(readme, block), encoding="utf-8")
        print(f"README.md: status block written ({block.count(chr(10))} lines)")
    else:
        sys.stdout.write(block + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
